export const Data =[
    {
        question: 'Week 1',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },
    {
        question: 'Week 2',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },
    {
        question: 'Week 3',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 4',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 5',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 6',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 7',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 8',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 9',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },  {
        question: 'Week 10',
        day1:'Day1 :React',
        day2:'Day2 :React',
        day3:'Day3 :React',
        day4:'Day4 :React',
        day5:'Day5 :React',
    },
]