# Generated by Django 3.1.4 on 2021-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0007_auto_20210128_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
                ('classes', models.ManyToManyField(blank=True, related_name='Link', to='lectures.Lecture')),
            ],
        ),
    ]
