# Generated by Django 3.1.4 on 2021-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('exercise', models.CharField(blank=True, max_length=200, verbose_name='exercise')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('expertise', models.CharField(blank=True, max_length=30, verbose_name='expertise')),
                ('date', models.DateField(blank=True, verbose_name='date')),
                ('programs', models.ManyToManyField(blank=True, related_name='lectures', to='lectures.Program')),
            ],
        ),
    ]
