# Generated by Django 3.1.4 on 2021-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20210127_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
