# Generated by Django 3.1.4 on 2021-01-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lectures', '0003_auto_20210127_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='lecture',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='weekday'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end_time')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='lectures.lecture')),
                ('speakers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classes_speaker', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='classes_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lectures.lectureweek'),
        ),
    ]
