# Generated by Django 3.1.4 on 2021-01-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20210128_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureweek',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='sort'),
        ),
    ]
