# Generated by Django 3.1.4 on 2021-01-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_lectureweek_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureweek',
            options={'ordering': ['sort']},
        ),
    ]
