# Generated by Django 3.1.4 on 2021-01-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20210128_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='weekday'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_time',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='start_time'),
        ),
    ]
