# Generated by Django 3.1.4 on 2021-01-27 09:55

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210126_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.user_profile_picture_directory),
        ),
    ]
