# Generated by Django 3.1.4 on 2021-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'administrator_ or another stuff member'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
