# Generated by Django 3.1.4 on 2021-02-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20210128_0926'),
        ('user', '0007_auto_20210130_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.program'),
        ),
    ]
